#!/usr/bin/env python3
"""Rebuild the combined RTR cell-line decomposition from PRISM Secondary and Primary inputs.

This script reconstructs the 578-cell-line combined RTR table from:
  * outputs/tables/prism_secondary_cell_line_context.csv generated by script 02
    from the Secondary dose-response file;
  * PRISM Primary replicate-collapsed logFC matrix;
  * outputs/tables/primary_drug_compound_annotations_selected.csv generated by
    script 01 from Primary treatment information and fixed curated labels;
  * Model.csv for lineage/name metadata;
  * OmicsSomaticMutations.csv for refined TP53 status when available.

The combined RTR score is the mean of the Secondary and Primary percentile ranks
of the repair-minus-removal response contrast. Primary-only cell lines therefore
receive their Primary percentile rank alone. This matches the manuscript's
coverage definition: 480 dual-evaluable + 98 Primary-only = 578 combined-score
cell lines.
"""
import os,sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import *
from pathlib import Path


def _first_col_as_depmap(df):
    first = df.columns[0]
    return df.rename(columns={first: 'depmap_id'})


def _median_across_columns(matrix, columns):
    columns = [c for c in columns if c in matrix.columns]
    if not columns:
        return pd.Series(np.nan, index=matrix.index)
    return matrix[columns].apply(pd.to_numeric, errors='coerce').median(axis=1)


def _load_primary_context():
    ann_path = TABLES/'primary_drug_compound_annotations_selected.csv'
    if not ann_path.exists():
        raise FileNotFoundError('Missing primary annotations. Run analysis/01_build_compound_annotations.py first.')
    require(PRISM_PRIMARY_MATRIX)
    ann = read(ann_path)
    if 'column_name' not in ann.columns:
        raise ValueError('primary_drug_compound_annotations_selected.csv must contain column_name')
    matrix = pd.read_csv(PRISM_PRIMARY_MATRIX, low_memory=False)
    matrix = _first_col_as_depmap(matrix)
    matrix = matrix.set_index('depmap_id')
    ann = ann[ann['column_name'].isin(matrix.columns)].copy()
    group_cols = {g: ann.loc[ann.analysis_group.eq(g), 'column_name'].astype(str).tolist()
                  for g in ['strict repair/protective','broad repair/protective','cytotoxic/removal-like']}
    any_repair_cols = group_cols['strict repair/protective'] + group_cols['broad repair/protective']
    out = pd.DataFrame({'depmap_id': matrix.index.astype(str)})
    out['primary_any_repair_median_logfc'] = _median_across_columns(matrix, any_repair_cols).values
    out['primary_removal_median_logfc'] = _median_across_columns(matrix, group_cols['cytotoxic/removal-like']).values
    out['primary_repair_preservation'] = out['primary_any_repair_median_logfc']
    out['primary_removal_vulnerability'] = -out['primary_removal_median_logfc']
    out['primary_RTR_delta_any_repair_minus_removal'] = out['primary_any_repair_median_logfc'] - out['primary_removal_median_logfc']
    out = out[out['primary_RTR_delta_any_repair_minus_removal'].notna()].copy()
    out['primary_repair_preservation_rank'] = out['primary_repair_preservation'].rank(pct=True)
    out['primary_removal_vulnerability_rank'] = out['primary_removal_vulnerability'].rank(pct=True)
    out['primary_RTR_delta_rank'] = out['primary_RTR_delta_any_repair_minus_removal'].rank(pct=True)
    return out


def _load_secondary_context():
    sec_path = TABLES/'prism_secondary_cell_line_context.csv'
    if not sec_path.exists():
        raise FileNotFoundError('Missing Secondary cell-line context. Run analysis/02_prism_repair_vs_removal_analysis.py first.')
    sec = read(sec_path)
    rename = {
        'any_repair_median_auc': 'secondary_any_repair_median_auc',
        'cytotoxic_median_auc': 'secondary_removal_median_auc',
        'repair_minus_removal_delta': 'secondary_RTR_delta_any_repair_minus_removal',
        'repair_preservation_rank': 'secondary_repair_preservation_rank',
        'removal_vulnerability_rank': 'secondary_removal_vulnerability_rank',
        'removal_vulnerability': 'secondary_removal_vulnerability',
    }
    sec = sec.rename(columns=rename)
    sec['secondary_repair_preservation'] = sec['secondary_any_repair_median_auc']
    sec['secondary_RTR_delta_rank'] = sec['secondary_RTR_delta_any_repair_minus_removal'].rank(pct=True)
    keep = ['depmap_id','secondary_repair_preservation','secondary_repair_preservation_rank',
            'secondary_removal_vulnerability','secondary_removal_vulnerability_rank',
            'secondary_any_repair_median_auc','secondary_removal_median_auc',
            'secondary_RTR_delta_any_repair_minus_removal','secondary_RTR_delta_rank']
    return sec[[c for c in keep if c in sec.columns]].copy()


def _load_model_metadata(depmap_ids):
    if not MODEL.exists():
        return pd.DataFrame({'depmap_id': list(depmap_ids)})
    model = read(MODEL)
    mid = 'ModelID' if 'ModelID' in model.columns else model.columns[0]
    model = model.rename(columns={mid:'depmap_id'})
    rename = {'CCLEName':'CCLEName','OncotreeLineage':'OncotreeLineage','OncotreePrimaryDisease':'OncotreePrimaryDisease'}
    cols = ['depmap_id'] + [c for c in rename if c in model.columns]
    return pd.DataFrame({'depmap_id': list(depmap_ids)}).merge(model[cols].drop_duplicates('depmap_id'), on='depmap_id', how='left')


def _load_tp53_status(depmap_ids):
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location('tp53mod', Path(__file__).with_name('05_tp53_interaction_tests.py'))
        mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
        if MUTATION.exists():
            mut = mod.read_mutation_for_tp53()
            return mod.assign_tp53_refined_status(mut, universe_ids=depmap_ids)
    except Exception as e:
        print('[warn] TP53 raw status could not be assigned:', e)
    return pd.DataFrame({'depmap_id': list(depmap_ids), 'TP53_refined_status': np.nan, 'any_TP53_LoF_high_impact': False})


def main():
    sec = _load_secondary_context()
    pri = _load_primary_context()
    cell = sec.merge(pri, on='depmap_id', how='outer')
    cell = cell[cell[['secondary_RTR_delta_any_repair_minus_removal','primary_RTR_delta_any_repair_minus_removal']].notna().any(axis=1)].copy()
    cell['RTR_score_combined_rank_0_1'] = cell[['secondary_RTR_delta_rank','primary_RTR_delta_rank']].mean(axis=1)
    cell['combined_repair_preservation_rank'] = cell[['secondary_repair_preservation_rank','primary_repair_preservation_rank']].mean(axis=1)
    cell['combined_removal_vulnerability_rank'] = cell[['secondary_removal_vulnerability_rank','primary_removal_vulnerability_rank']].mean(axis=1)
    cell['combined_RTR_quadrant'] = [quadrant(a,b) for a,b in zip(cell.combined_repair_preservation_rank, cell.combined_removal_vulnerability_rank)]
    meta = _load_model_metadata(cell['depmap_id'])
    tp53 = _load_tp53_status(cell['depmap_id'])
    cell = meta.merge(tp53, on='depmap_id', how='left').merge(cell, on='depmap_id', how='right')
    cell['RTR_score_formula_note'] = 'mean of available Secondary and Primary percentile ranks of repair-minus-removal response contrast; Primary-only lines use the Primary rank alone'
    cell = cell.sort_values('RTR_score_combined_rank_0_1', ascending=False).reset_index(drop=True)
    cell['RTR_high_removal_high_quadrant_combined'] = cell.combined_RTR_quadrant.eq('repair-high / removal-high')
    cell['RTR_high_top20pct'] = cell.RTR_score_combined_rank_0_1 >= 0.8
    cell['RTR_low_bottom20pct'] = cell.RTR_score_combined_rank_0_1 <= 0.2

    save(cell, 'cell_line_RTR_scores_with_quadrants_and_variants.csv')
    # Also write the decomposition filename into outputs/tables for manuscript-supporting checks.
    save(cell, 'RTR_combined_decomposition_578_rebuilt_from_raw.csv')

    cols = ['depmap_id','RTR_score_combined_rank_0_1','combined_RTR_quadrant',
            'combined_repair_preservation_rank','combined_removal_vulnerability_rank',
            'secondary_repair_preservation_rank','secondary_removal_vulnerability_rank',
            'primary_repair_preservation_rank','primary_removal_vulnerability_rank',
            'RTR_high_top20pct','RTR_low_bottom20pct','RTR_high_removal_high_quadrant_combined']
    save(cell[[c for c in cols if c in cell.columns]], 'RTR_score_decomposed_repair_preservation_removal_vulnerability.csv')

    rows=[]
    for c in ['combined_repair_preservation_rank','combined_removal_vulnerability_rank',
              'secondary_repair_preservation_rank','secondary_removal_vulnerability_rank']:
        rho,p = spearman(cell[c], cell.RTR_score_combined_rank_0_1)
        rows.append(dict(component=c, n=int(cell[c].notna().sum()), median=cell[c].median(), mean=cell[c].mean(), corr_with_RTR_spearman=rho, corr_with_RTR_p=p))
    df=pd.DataFrame(rows); df['fdr_corr_with_RTR']=bh_fdr(df.corr_with_RTR_p)
    save(df, 'RTR_component_summary_and_correlations.csv')

if __name__=='__main__':
    main()
